FROM openjdk:10-jre-slim
COPY ./target/web.api-0.0.1-SNAPSHOT.jar /Web.API/src/main/java/com.example/FirstWebAPI
WORKDIR /Web.API/src/main/java/com.example/FirstWebAPI
EXPOSE 8080
CMD ["java", "-jar", "web.api-0.0.1-SNAPSHOT.jar"]
